### ISSUE TITLE
Project ID suggestions

### ISSUE THREAD

**Issue by joseale2310** [brickmanlab/ngs-template#1]
Project ID should have full date: YYYYMMDD
Project ID should have initials of author instead of <surname>_et_al_YYYYMMDD
Project ID should be written with "_" instead of "-"

Example:
MP_20230101 instead of proks-et-al-20230101)

Probably the ID should also include one short keyword to help with visibility.

**Comment by matq007** [comment]
I think the latest update by @SLundregan is good enough that it makes it versatile enough. What do you think?
